// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkiG1jIKDktwi0rU1tAwGOdC_SFrD2s4k',
    appId: '1:1031841429357:web:9a16b867d2815efb98cc64',
    messagingSenderId: '1031841429357',
    projectId: 'chat-app-f0c52',
    authDomain: 'chat-app-f0c52.firebaseapp.com',
    storageBucket: 'chat-app-f0c52.firebasestorage.app',
    measurementId: 'G-FM42SY7RJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0aXBjDAqIF4hhTZL0Iv50KhkH_0jb0Zo',
    appId: '1:1031841429357:android:a3493564a8b4a7a698cc64',
    messagingSenderId: '1031841429357',
    projectId: 'chat-app-f0c52',
    storageBucket: 'chat-app-f0c52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl3x6SurtUYd1kYN6oKzLxqTpg_MXN3zM',
    appId: '1:1031841429357:ios:77457eb1a2a25dce98cc64',
    messagingSenderId: '1031841429357',
    projectId: 'chat-app-f0c52',
    storageBucket: 'chat-app-f0c52.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl3x6SurtUYd1kYN6oKzLxqTpg_MXN3zM',
    appId: '1:1031841429357:ios:77457eb1a2a25dce98cc64',
    messagingSenderId: '1031841429357',
    projectId: 'chat-app-f0c52',
    storageBucket: 'chat-app-f0c52.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkiG1jIKDktwi0rU1tAwGOdC_SFrD2s4k',
    appId: '1:1031841429357:web:1579562a4e64977a98cc64',
    messagingSenderId: '1031841429357',
    projectId: 'chat-app-f0c52',
    authDomain: 'chat-app-f0c52.firebaseapp.com',
    storageBucket: 'chat-app-f0c52.firebasestorage.app',
    measurementId: 'G-FPV1K1J2W9',
  );
}
